### ISSUE TITLE
Add Sophi Site Automation API call logging

### ISSUE THREAD

**Issue by jeffpaul** [Mather-Sophi/sp-debug-bar-for-sophi#15]
### Is your enhancement related to a problem? Please describe.

When we make a call to the Sophi Site Automation API, it would be helpful to have the Debug Bar show:
- API request
- Sophi response (expected a list of Post IDs)
- any success/failure messages associated with the request and response

Ideally we can see this info in the editor as well as when viewing a post on the front-end.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cadic** [comment]
@jeffpaul we actually DO display every request the Sophi plugin performs in Site Automation workflow. The problem is that the request is performed not on every page load.

The main plugin has 2-level caching within Query Integration:

In the render_block_callback, [we read curated posts](https://github.com/globeandmail/sophi-for-wordpress/blob/434a183500d62b01691f9abf453c92b9b85ec5f3/includes/blocks/site-automation-block/register.php#L43-L45) from the transient: **first-level cache**, TTL 5 minutes:

```php
$curated_posts_transient_key = 'sophi_curated_posts_' . $page_name . '_' . $widget_name;

$curated_posts = get_transient( $curated_posts_transient_key );

if ( false === $curated_posts ) {
	// phpcs:ignore WordPressVIPMinimum.Functions.RestrictedFunctions.get_posts_get_posts
	$curated_posts = get_posts(
		[
			'sophi_curated_page'   => $page_name,
			'sophi_curated_widget' => $widget_name,
		]
	);

	if ( empty( $curated_posts ) ) {
		return '';
	}

	set_transient( $curated_posts_transient_key, $curated_posts, 5 * MINUTE_IN_SECONDS );
}
```

Then, if the transient doesn't exist, we perform the request in SophiWP\SiteAutomation\Integration::get_curated_posts() which is [cached in the post meta](https://github.com/globeandmail/sophi-for-wordpress/blob/434a183500d62b01691f9abf453c92b9b85ec5f3/includes/classes/SiteAutomation/Request.php#L107-L109):

```php
if ( ! $bypass_cache ) {
	$site_automation_data = get_post_meta( $this->post_id, "_sophi_site_automation_data_{$this->page}_{$this->widget}", true );
}
```

**Comment by jeffpaul** [comment]
Could we expose those cache requests then to see that we're requesting the "correct" info and then what WP is returning from cache?

**Comment by cadic** [comment]
To make sure that main Sophi plugin is doing remote requests each time, in the Debug Bar for Sophi plugin we can:

1. Hook into the transient set or get and suppress all transients masked with `sophi_curated_posts_*` — it will force the block render function to always request dynamic data.
2. Force `sophi_bypass_get_cache` filter to return true — it will stop Sophi from getting block data from post meta

**Comment by cadic** [comment]
Probably worth adding another checkbox to the plugin settings

**Comment by jeffpaul** [comment]
@cadic ah yeah, that actually would be worthwhile as well.  Perhaps something like:
>  [ ] Disable WordPress caching of Sophi content
^ unchecked by default?

**Comment by cadic** [comment]
@jeffpaul since the transient name is variable, we cannot hook into the set_transient or get_transient because WordPress core is using strict transient name only and doesn't allow to filter all transients.

In this case I suggest to add another filter `sophi_bypass_curated_posts_cache` around here: https://github.com/globeandmail/sophi-for-wordpress/blob/434a183500d62b01691f9abf453c92b9b85ec5f3/includes/blocks/site-automation-block/register.php#L43-L50

**Comment by jeffpaul** [comment]
@cadic is there more you want to / can add on this issue or should this be closed out?
